on:
  schedule:
    - cron:  '25 14 * * *'

jobs:
  message:
    runs-on: ubuntu-latest
    steps:
    - name: Discord Webhook Action
      uses: tsickert/discord-webhook@v7.0.0
      with:
        webhook-url: ${{ https://discord.com/api/webhooks/1363882091292659954/yWEQLzKyO_VgsVn3te02oBLxqtDObpGuXaiuJgZOSvVtlfUTFYg1JsUTzGMXQJV0jZ12 }}
        content: "Test"
